public class Player {
    public void playing(){
        String player1Name = 'Dürdane';
        System.debug(player1Name);
        String player2Name = 'Pakize';
        System.debug(player2Name);
        String player3Name = 'Hatice';
        System.debug(player3Name);
        String player4Name = 'Safiye';
        System.debug(player4Name);
        String player5Name = 'Zeliha';
        System.debug(player5Name);


    }
}
